"""atualizando tabela para tokens

Revision ID: d306e4a964f7
Revises: 4d04e715f587
Create Date: 2024-09-02 19:49:13.120552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd306e4a964f7'
down_revision: Union[str, None] = '4d04e715f587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
